ALTER TABLE APOENSKA_STRUKTURA_PROMETA ADD (
  CONSTRAINT AS_PROMETA_APOEN_FK 
 FOREIGN KEY (ID_APOEN) 
 REFERENCES APOEN (ID_APOEN),
  CONSTRAINT AS_PROMETA_PROMET_FK 
 FOREIGN KEY (ID_PROMET) 
 REFERENCES PROMET (ID_PROMET));
