ALTER TABLE APOENSKA_STRUKTURA_BLAGAJNE ADD (
  CONSTRAINT AS_BLAGAJNE_APOEN_FK 
 FOREIGN KEY (ID_APOEN) 
 REFERENCES APOEN (ID_APOEN),
  CONSTRAINT AS_BLAGAJNE_BLAGAJNA_FK 
 FOREIGN KEY (ID_BLAGAJNA) 
 REFERENCES BLAGAJNA (ID_BLAGAJNA));
