ALTER TABLE PROMET ADD (
  CONSTRAINT PROMET_BLAGAJNA_FK 
 FOREIGN KEY (ID_BLAGAJNA) 
 REFERENCES BLAGAJNA (ID_BLAGAJNA),
  CONSTRAINT PROMET_VRSTA_PROMETA_FK 
 FOREIGN KEY (ID_VRSTA_PROMETA) 
 REFERENCES VRSTA_PROMETA (ID_VRSTA_PROMETA));
