ALTER TABLE TRANSAKCIJA_ZA_KOMITENTA ADD (
  CHECK ("ID_TRANSAKCIJA_ZA_KOMITENTA" IS NOT NULL) DISABLE,
  CHECK ("ID_UGOVOR" IS NOT NULL) DISABLE,
  CHECK ("SIFRA_KOMITENTA" IS NOT NULL) DISABLE,
  CHECK ("ID_UGOVORENA_USLUGA" IS NOT NULL) DISABLE,
  CHECK ("ID_VRSTA_TRANSAKCIJE" IS NOT NULL) DISABLE,
  CHECK ("VRSTA_ZAPISA" IS NOT NULL) DISABLE,
  CHECK ("SIFRA_TRANSAKCIJE" IS NOT NULL) DISABLE,
  CHECK ("OPIS" IS NOT NULL) DISABLE,
  CHECK ("MODEL_POZIVA_NA_BROJ" IS NOT NULL) DISABLE,
  CHECK ("DUZINA_POZIVA_NA_BROJ_OD" IS NOT NULL) DISABLE,
  CHECK ("DUZINA_POZIVA_NA_BROJ_DO" IS NOT NULL) DISABLE,
  CHECK ("ONLINE_DN" IS NOT NULL) DISABLE,
  CHECK ("TRANSFER_DN" IS NOT NULL) DISABLE,
  CONSTRAINT TRANSAKCIJA_ZA_KOMITENTA_PK
 PRIMARY KEY
 (ID_TRANSAKCIJA_ZA_KOMITENTA) DISABLE);
