ALTER TABLE TRANSAKCIJA_BANKA ADD (
  CONSTRAINT TRANSAKCIJA_BANKA_DNEVNIK_FK 
 FOREIGN KEY (ID_DNEVNIK_TRANSAKCIJA) 
 REFERENCES DNEVNIK_TRANSAKCIJA (ID_DNEVNIK_TRANSAKCIJA),
  CONSTRAINT TRANSAKCIJA_BANKA_NALOG_PP_FK 
 FOREIGN KEY (ID_TRANSAKCIJA_NALOG_PP) 
 REFERENCES TRANSAKCIJA_NALOG_PP (ID_TRANSAKCIJA_NALOG_PP));
