ALTER TABLE TRANSAKCIJA_KOMITENT ADD (
  CONSTRAINT TRANS_KOMITENT_DNEVNIK_FK 
 FOREIGN KEY (ID_DNEVNIK_TRANSAKCIJA) 
 REFERENCES DNEVNIK_TRANSAKCIJA (ID_DNEVNIK_TRANSAKCIJA),
  CONSTRAINT TRANS_KOMITENT_NALOG_PP_FK 
 FOREIGN KEY (ID_TRANSAKCIJA_NALOG_PP) 
 REFERENCES TRANSAKCIJA_NALOG_PP (ID_TRANSAKCIJA_NALOG_PP));
