CREATE TABLE APOEN
(
  ID_APOEN            NUMBER(3)                 NOT NULL,
  ID_VALUTA           NUMBER(3)                 NOT NULL,
  NOMINALNA_VREDNOST  NUMBER(18,2),
  STATUS              VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


