CREATE TABLE APOEN_STRUKTURA_MANJKA_VISKA
(
  ID_MANJAK_VISAK  NUMBER(9)                    NOT NULL,
  ID_APOEN         NUMBER(3)                    NOT NULL,
  KOMADA           NUMBER(5)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


