CREATE TABLE ARH_CPM_OBRADA
(
  ID_CPM_DAN                  RAW(16)           NOT NULL,
  OBRADA_BANKE                VARCHAR2(1 CHAR),
  OBRADA_KOMITENTI            VARCHAR2(1 CHAR),
  OBRADA_NALOG_PP             VARCHAR2(1 CHAR),
  ID_CPM                      NUMBER(5)         NOT NULL,
  DATUM                       DATE              NOT NULL,
  KREIRANJE_PRIJAVA_BANKA     VARCHAR2(1 CHAR),
  KREIRANJE_PRIJAVA_KOMITENT  VARCHAR2(1 CHAR),
  OBRADA_PRIJAVA              VARCHAR2(1 CHAR),
  OBRADA_DNEVNIKA             VARCHAR2(1 CHAR),
  FAJL_DN                     VARCHAR2(1 CHAR),
  FAJL_LOK_KOMITENT_DN        VARCHAR2(1 CHAR),
  OBRADA_BLAGAJNE             VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


