CREATE TABLE ARH_TRANSAKCIJA_KOMITENT
(
  ID_TRANSAKCIJA_KOMITENT  NUMBER(9)            NOT NULL,
  SIFRA_KOMITENTA          VARCHAR2(5 CHAR)     NOT NULL,
  IZNOS                    NUMBER(18,2)         NOT NULL,
  PROCENAT_POPUSTA         NUMBER(18,2),
  IZNOS_SA_POPUSTOM        NUMBER(18,2),
  POZIV_NA_BROJ            VARCHAR2(22 CHAR),
  ID_CPM                   NUMBER(5)            NOT NULL,
  DATUM                    DATE                 NOT NULL,
  ID_VRSTA_TRANSAKCIJE     NUMBER(5)            NOT NULL,
  ID_RADNIK                NUMBER(8)            NOT NULL,
  REDNI_BROJ_TRANSAKCIJE   VARCHAR2(5 CHAR)     NOT NULL,
  STATUS                   VARCHAR2(1 CHAR)     NOT NULL,
  ID_TRANSAKCIJA_NALOG_PP  NUMBER(9),
  ID_DNEVNIK_TRANSAKCIJA   NUMBER(9),
  DATUM_TRANSAKCIJE        DATE,
  SIFRA_TRANSAKCIJE        VARCHAR2(5 CHAR),
  SIFRA_RADNIKA            VARCHAR2(4 CHAR),
  MODEL_POZIVA_NA_BROJ     VARCHAR2(2 CHAR),
  ID_CPM_DAN               RAW(16),
  DOSTAVA                  VARCHAR2(1 CHAR),
  SALTER                   NUMBER(5)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


