CREATE TABLE DNEVNIK_TRANSAKCIJA
(
  ID_DNEVNIK_TRANSAKCIJA  NUMBER(9),
  ZA_DAN                  DATE,
  ID_CPM                  NUMBER(5),
  DATUM_PRIPREME          DATE,
  DATUM_SLANJA            DATE,
  FAJL                    VARCHAR2(100 CHAR),
  VRSTA_KOMITENTA         VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


