CREATE TABLE IZV_SO_TRN
(
  ID_IZV_SO_TRN           NUMBER(5),
  ID_CPM_DAN              RAW(16)               NOT NULL,
  ID_TRANSAKCIJA          RAW(16)               NOT NULL,
  RJ                      VARCHAR2(70 CHAR)     NOT NULL,
  POSTA                   VARCHAR2(5 CHAR)      NOT NULL,
  DATUM_TRANSAKCIJE       DATE,
  DATUM_STORNO_OPOZIV     DATE,
  SIFRA_TRANSAKCIJE       NUMBER(5),
  NAZIV_TRN               VARCHAR2(50 CHAR),
  SIFRA_RADNIKA           VARCHAR2(6 CHAR),
  RBR_TRANSAKCIJE         NUMBER(5),
  IZNOS                   NUMBER(18,2),
  POSTARINA               NUMBER(18,2),
  OPIS_I                  VARCHAR2(50 CHAR),
  OPIS_II                 VARCHAR2(50 CHAR),
  OPIS_III                VARCHAR2(50 CHAR),
  RAZLOG_STORNO_OPOZIV    VARCHAR2(400 CHAR),
  BROJ_S_O_TRANSAKCIJE    VARCHAR2(50 CHAR),
  DATUM_NOVE_TRN          DATE,
  SIFRA_NOVE_TRN          VARCHAR2(5 CHAR),
  SIFRA_RADNIKA_NOVE_TRN  VARCHAR2(6 CHAR),
  RBR_NOVE_TRN            NUMBER(5),
  IZNOS_NOVE_TRN          NUMBER(18,2),
  POSTARINA_NOVE_TRN      NUMBER(18,2),
  OPIS_I_NOVE_TRN         VARCHAR2(50 CHAR),
  OPIS_II_NOVE_TRN        VARCHAR2(50 CHAR),
  OPIS_III_NOVE_TRN       VARCHAR2(50 CHAR),
  STATUS                  VARCHAR2(1 CHAR),
  ID_IZVOR_PODATAKA       NUMBER(1)             NOT NULL,
  DATUM_PUNJENJA          DATE                  NOT NULL,
  OBRACUNSKI_DAN          DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


