CREATE TABLE IZV_NALOZI
(
  ID_IZV_NALOZI      NUMBER(7)                  NOT NULL,
  ID_CPM_DAN         RAW(16)                    NOT NULL,
  ID_TRANSAKCIJA     RAW(16)                    NOT NULL,
  SIFRA_TRN          NUMBER(5)                  NOT NULL,
  NAZIV_TRN          VARCHAR2(50 CHAR)          NOT NULL,
  POSTANSKI_BROJ     VARCHAR2(5 CHAR)           NOT NULL,
  DATUM_UPLATE       DATE                       NOT NULL,
  SIFRA_RADNIKA      VARCHAR2(6 CHAR)           NOT NULL,
  RBR_TRANSAKCIJE    NUMBER(5)                  NOT NULL,
  IZNOS              NUMBER(18,2)               NOT NULL,
  TEKUCI_RACUN       VARCHAR2(18 CHAR)          NOT NULL,
  POZIV_NA_BROJ      VARCHAR2(18 CHAR),
  SIFRA_PLACANJA     NUMBER(3),
  MODEL              VARCHAR2(3 CHAR),
  UPLATILAC_I        VARCHAR2(35 CHAR)          NOT NULL,
  UPLATILAC_II       VARCHAR2(35 CHAR),
  UPLATILAC_III      VARCHAR2(35 CHAR),
  SVRHA_UPLATE_I     VARCHAR2(35 CHAR)          NOT NULL,
  SVRHA_UPLATE_II    VARCHAR2(35 CHAR),
  SVRHA_UPLATE_III   VARCHAR2(35 CHAR),
  PRIMALAC_I         VARCHAR2(35 CHAR)          NOT NULL,
  PRIMALAC_II        VARCHAR2(35 CHAR),
  PRIMALAC_III       VARCHAR2(35 CHAR),
  RJ                 VARCHAR2(50 CHAR)          NOT NULL,
  ID_IZVOR_PODATAKA  NUMBER(1)                  NOT NULL,
  DATUM_PUNJENJA     DATE                       NOT NULL,
  OBRACUNSKI_DAN     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


