CREATE TABLE PRIJAVA
(
  ID_PRIJAVA     NUMBER(3)                      NOT NULL,
  NAZIV_PRIJAVE  VARCHAR2(50 CHAR),
  VRSTA_PRIJAVE  VARCHAR2(1 CHAR),
  UPLATILAC      VARCHAR2(35 CHAR),
  PRIMALAC       VARCHAR2(35 CHAR),
  RACUN_RJ       VARCHAR2(1 CHAR),
  GRUPA          VARCHAR2(50 CHAR),
  STATUS         VARCHAR2(1 CHAR)               DEFAULT 'A'                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


