CREATE TABLE STANJE_KASE
(
  ID_CPM_DAN       RAW(16),
  POCETNO_STANJE   NUMBER(18,2),
  DOTACIJA         NUMBER(18,2),
  UPLATA           NUMBER(18,2),
  SUVISAK          NUMBER(18,2),
  ISPLATA          NUMBER(18,2),
  NERAZDUZEN_REON  NUMBER(18,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


