CREATE TABLE TEKUCI_RACUN_RJ
(
  ID_TEKUCI_RACUN_RJ  NUMBER(3)                 NOT NULL,
  ID_RJ               NUMBER(5)                 NOT NULL,
  TEKUCI_RACUN        VARCHAR2(20 CHAR)         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


