CREATE TABLE TRANSAKCIJA_ZA_BANKU
(
  ID_TRANSAKCIJA_ZA_BANKU      NUMBER(7)        NOT NULL,
  ID_VRSTA_TRANSAKCIJE         NUMBER(7)        NOT NULL,
  ID_UGOVOR                    NUMBER(7)        NOT NULL,
  ID_UGOVORENA_USLUGA          NUMBER(7)        NOT NULL,
  SIFRA_BANKE_KOMITENTA        VARCHAR2(5 CHAR) NOT NULL,
  SIFRA_BANKE                  VARCHAR2(5 CHAR) NOT NULL,
  SIFRA_TRANSAKCIJE            VARCHAR2(5 CHAR) NOT NULL,
  PREDMET_TRANSAKCIJE          VARCHAR2(10 CHAR) NOT NULL,
  MODEL_TEKUCI_RACUN           VARCHAR2(5 CHAR),
  MODEL_BROJ_CEKA              VARCHAR2(5 CHAR),
  MINIMALNI_IZNOS              NUMBER(15,2)     NOT NULL,
  MAKSIMALNI_IZNOS             NUMBER(15,2)     NOT NULL,
  ONLINE_DN                    VARCHAR2(1 CHAR) NOT NULL,
  AUTORIZACIJA_DN              VARCHAR2(1 CHAR) NOT NULL,
  LICNI_DOKUMENT_DN            VARCHAR2(1 CHAR) NOT NULL,
  IME_PREZIME_DN               VARCHAR2(1 CHAR) NOT NULL,
  ADRESA_DN                    VARCHAR2(1 CHAR) NOT NULL,
  STANJE_NAKON_TRANSAKCIJE_DN  VARCHAR2(1 CHAR) NOT NULL,
  REDNI_BROJ_REDA_DN           VARCHAR2(1 CHAR) NOT NULL,
  TRANSFER_DN                  VARCHAR2(1 CHAR) NOT NULL,
  TRANSFER_FORMAT              VARCHAR2(20 CHAR),
  TRANSFER_EKSTENZIJA          VARCHAR2(20 CHAR),
  TRANSFER_KANAL               VARCHAR2(20 CHAR),
  VRSTA_TRANSAKCIJE_UI         VARCHAR2(1 CHAR),
  VRSTA_OVERE                  VARCHAR2(20 CHAR) NOT NULL,
  VAZI_OD                      DATE,
  VAZI_DO                      DATE,
  KONSTANTA_U_POZIVU_NA_BROJ   VARCHAR2(10 CHAR),
  VRSTA_PROMENE                VARCHAR2(5 CHAR),
  SIFRA_PLACANJA               NUMBER(5),
  ID_PRIJAVA                   NUMBER(3)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


