CREATE TABLE VRSTA_PROMETA
(
  ID_VRSTA_PROMETA  NUMBER(3)                   NOT NULL,
  OPIS              VARCHAR2(50 CHAR),
  STATUS            VARCHAR2(1 CHAR),
  OPIS_PROMETA      VARCHAR2(50 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


