CREATE OR REPLACE PACKAGE                    F9_PACKAGE is
TYPE T_CURSOR IS REF CURSOR;
PROCEDURE UGOVOR_F9(P_DELOVODNI_BROJ UGOVOR.DELOVODNI_BROJ%TYPE,
                    P_DATUM          IN VARCHAR2,
                    P_CURSOR         OUT T_CURSOR);

PROCEDURE KOMITENT_F9(P_ID_UGOVOR IN UGOVOR_POSLOVNOG_PARTNERA.ID_UGOVOR%TYPE,
                      P_NAZIV_F9  IN POSLOVNI_PARTNER.NAZIV_F9%TYPE,
                      P_CURSOR    OUT T_CURSOR);

PROCEDURE UGOVORENA_USLUGA_F9(P_ID_UGOVOR IN UGOVORENA_USLUGA.ID_UGOVOR%TYPE,
                              P_NAZIV     IN USLUGE.NAZIV%TYPE,
                              P_CURSOR    OUT T_CURSOR);

PROCEDURE KOMITENT_PRETRAGA_F9(P_NAZIV_F9 IN POSLOVNI_PARTNER.NAZIV_F9%TYPE,
                               P_CURSOR   OUT T_CURSOR);
                               
PROCEDURE PRIJAVA_PRETRAGA_F9(P_CURSOR OUT T_CURSOR);

 PROCEDURE KOMITENT_NAZIV_F9(                              
                                 P_ID_CPM_DAN IN TRANSAKCIJA_KOMITENT.ID_CPM_DAN%TYPE,
                                 P_CURSOR   OUT T_CURSOR);

END F9_PACKAGE;
/

SHOW ERRORS;


